// LUMORANI — UI-Dictionary (DE = Quelle der Wahrheit, EN gepflegt).
// Namespaces spiegeln die Bausteine der Seite. Produkt-/Edelstein-/Rechtstexte
// liegen im Katalog bzw. in den jeweiligen Seiten, nicht hier.

import type { Locale } from "@/lib/i18n";

const de = {
  common: {
    brandTagline: "Echte Edelsteine. Zeitloses Design.",
    allProducts: "Alle Produkte",
    shopAll: "Alle Stücke",
    viewGemstones: "Alle Edelsteinarten",
    backToShop: "Zurück zum Shop",
    from: "ab",
    loading: "Wird geladen …",
  },
  nav: {
    announcement: "Versandkostenfrei innerhalb Deutschlands · info@lumorani.com",
    shop: "Shop",
    gemstones: "Edelsteine",
    giftsets: "Geschenksets",
    about: "Über uns",
    start: "Start",
    contact: "Kontakt",
    search: "Suche",
    cart: "Warenkorb",
    menuOpen: "Menü öffnen",
    menuClose: "Menü schließen",
    langLabel: "Sprache",
  },
  footer: {
    blurb: "Echte Edelsteine. Zeitloses Design. Ein Familienunternehmen von Samir und seinem Vater.",
    colCollections: "Kollektionen",
    colService: "Service",
    colLegal: "Rechtliches",
    l_shipping: "Lieferung und Versand",
    l_returns: "Rückgaberichtlinien",
    l_faq: "Meistgestellte Fragen",
    l_contact: "Kontakt",
    l_imprint: "Impressum",
    l_privacy: "Datenschutzerklärung",
    l_terms: "AGB",
    l_accessibility: "Barrierefreiheit",
    occ_anfang: "Für jeden Anfang",
    occ_alltag: "Für jeden Tag",
    occ_statement: "Statement",
    occ_geschenk: "Zum Verschenken",
    rights: "LUMORANI",
    handmade: "Handgefertigt in Deutschland",
  },
  hero: {
    eyebrow: "Echte Edelsteine · Zeitloses Design",
    titleTop: "Schmuck, der",
    titleBottom: "Emotionen trägt",
    sub: "Für Menschen, die sich mit Stil ausdrücken wollen.",
    ctaPrimary: "Kollektion entdecken",
    ctaSecondary: "Edelsteine ansehen",
  },
  home: {
    collectionsEyebrow: "Kollektionen",
    collectionsTitle: "Für jeden Moment der richtige Stein",
    storyEyebrow: "Unsere Geschichte",
    storyTitle: "Momente, die bleiben",
    storyLead:
      "Schmuck begleitet uns in Momenten, die bleiben. Ein Geschenk, ein Anfang, ein Gefühl. Deshalb erschaffen wir Stücke, die Bedeutung tragen.",
    storyBody:
      "Mit Liebe von Samir und seinem Vater ausgewählt, steht jedes Schmuckstück für Echtheit, Tiefe und Persönlichkeit. Wir glauben an klare Formen, starke Farben und Designs, die sich wie ein Teil von dir anfühlen.",
    storyCta: "Über Lumorani",
    newsEyebrow: "Neuheiten",
    newsTitle: "Frisch aus der Werkstatt",
    quote:
      "Unsere Kollektion kombiniert tiefe Rubintöne, intensives Smaragdgrün und klare metallische Akzente.",
    voicesEyebrow: "Kundenstimmen",
    voicesTitle: "Was unsere Kundinnen sagen",
  },
  trust: {
    handmade: "Handgefertigt",
    handmadeSub: "In liebevoller Handarbeit gefertigt",
    natural: "Echte Natursteine",
    naturalSub: "Handverlesene Edelsteine, jeder ein Unikat",
    shipping: "Versandkostenfrei",
    shippingSub: "Innerhalb Deutschlands ab 0 €",
    family: "Familienmanufaktur",
    familySub: "Von Samir und seinem Vater",
  },
  newsletter: {
    eyebrow: "Newsletter",
    title: "Neue Unikate zuerst.",
    body: "Trag dich ein und erfahre als Erste*r von neuen Stücken, seltenen Steinen und besonderen Momenten. Kein Spam – nur das, was wirklich glänzt.",
    emailLabel: "E-Mail*",
    emailPlaceholder: "name@mail.de",
    submit: "Einreichen",
    thanks: "Danke. Du hörst als Erste*r von uns.",
    pending: "Wird angemeldet …",
    consent: "Mit der Anmeldung stimmst du dem Newsletter-Empfang zu. Eingetragen wirst du erst nach Klick auf den Bestätigungslink.",
    error: "Das hat nicht geklappt. Bitte versuch es erneut.",
  },
  cart: {
    title: "Warenkorb",
    close: "Schließen",
    empty: "Noch nichts ausgewählt. Entdecke unsere Lieblinge.",
    giftWrap: "Als Geschenk verpacken (+0 €)",
    giftPlaceholder: "Grußbotschaft (optional) – wir legen sie handschriftlich bei.",
    promoPlaceholder: "Gutscheincode",
    promoHint: "an der Kasse",
    sum: "Summe",
    checkout: "Zur Kasse",
    checkoutLoading: "Einen Moment …",
    reassurance: "Sichere Zahlung über Stripe · Versichert versandt · 14 Tage Rückgabe",
    errUnavailable: "Der Checkout ist gerade nicht verfügbar.",
    errNetwork: "Netzwerkfehler. Bitte versuch es noch einmal.",
  },
  shop: {
    crumbShop: "Shop",
    eyebrowShop: "Shop",
    eyebrowCollection: "Kollektion",
    titleAll: "Alle Schmuckstücke",
    searchLabel: "Produkte suchen",
    searchPlaceholder: "Name, Stein oder Kategorie",
    showAll: "Alle Produkte zeigen",
    filterAll: "Alle",
    selStone: "Stein",
    selPrice: "Preis",
    selSort: "Sortieren",
    allStones: "Alle Steine",
    priceAll: "Alle Preise",
    priceUnder25: "bis 25 €",
    price25to60: "25–60 €",
    priceOver60: "über 60 €",
    sortRecommended: "Empfohlen",
    sortPriceAsc: "Preis aufsteigend",
    sortPriceDesc: "Preis absteigend",
    countOne: "Stück",
    countMany: "Stücke",
    emptyEyebrow: "Noch nicht dabei?",
    emptyTitle: "Dein Stein wartet vielleicht noch in Samirs Werkstatt.",
    emptyBody:
      "Für diese Auswahl haben wir gerade kein fertiges Stück. Sag uns, wonach du suchst – Farbe, Stein, Anlass – und wir schauen, was sich finden oder von Hand fertigen lässt.",
    emptyCta: "Individuelle Anfrage senden",
    resetFilters: "Filter zurücksetzen",
  },
  product: {
    add: "In den Warenkorb",
    trust1: "Handgefertigtes Unikat",
    trust2: "Versichert versandt",
    trust3: "14 Tage Rückgabe",
    factMaterial: "Material",
    factCharacter: "Charakter",
    factMaking: "Fertigung",
    factCare: "Pflege",
    factDelivery: "Lieferzeit",
    factMaterialFallback: "Naturstein, handgefertigt",
    factCharacterFallback: "Handverlesenes Unikat",
    factMakingValue: "Handgefertigtes Unikat",
    factCareFallback: "Weiches Tuch, lauwarmes Wasser",
    factDeliveryValue: "3–5 Werktage, versichert",
    samirNote: "Samirs Notiz",
    samirRole: "Samir · Gründer & Steinsucher",
    related: "Passt dazu",
    shotProduct: "Produktansicht",
    shotBox: "In der LUMORANI-Box",
    shotCollection: "Kollektion",
  },
  gemstones: {
    eyebrow: "Edelsteine",
    title: "Die Vielfalt unserer Edelsteine",
    subtitle:
      "Mit großer Sorgfalt ausgewählt – von naturbelassenen Rohsteinen über präzise geschliffene Kristalle bis zu modernen „Half & Half“-Formen. Jeder Stein trägt seine eigene Energie, Struktur und Persönlichkeit.",
    cutRawT: "Ungeschliffen",
    cutRawB: "Roh, naturbelassen, authentisch. Der Stein, wie die Natur ihn geformt hat.",
    cutFacetedT: "Geschliffen",
    cutFacetedB: "Facettiert und poliert. Präzise Kanten, die das Licht brechen.",
    cutHalfT: "Half & Half",
    cutHalfB: "Halb roh, halb geschliffen — der Kontrast für moderne, ausdrucksstarke Designs.",
    closing:
      "Diese Vielfalt macht unsere Steine ideal für Sammler, Schmuckliebhaber, Gestalter und alle, die besondere Materialien schätzen.",
  },
  gift: {
    eyebrow: "Zum Verschenken",
    title: "Ein Geschenk, das bleibt",
    sub: "Sorgfältig gewählt. Von Hand verpackt. Mit Bedeutung. Schenke keinen Gegenstand – schenke einen Moment.",
    p1t: "In der LUMORANI-Box",
    p1b: "Jedes Geschenk kommt von Hand verpackt in unserer emeraldgrünen Box mit Goldplakette. Die Verpackung kann von der Abbildung leicht abweichen.",
    p2t: "Mit Echtheit",
    p2b: "Nur echte Natursteine, handverlesen von Samir. Jedes Stück ist ein Unikat.",
    p3t: "Versichert versandt",
    p3b: "Sicher verpackt, versichert verschickt – und 14 Tage Rückgaberecht.",
    recEyebrow: "Unsere Empfehlung",
    recTitle: "Kuratierte Geschenke",
    allGifts: "Alle Geschenke",
    undecidedEyebrow: "Noch unentschlossen?",
    undecidedTitle: "Finde das passende Geschenk",
    ctaMilestone: "Für einen Meilenstein",
    ctaEveryday: "Für jeden Tag",
    ctaByStone: "Nach Stein & Bedeutung",
  },
  success: {
    eyebrow: "Vielen Dank",
    title: "Deine Bestellung ist bei uns.",
    body: "Wir bereiten dein Stück jetzt von Hand vor und verpacken es sorgfältig in der LUMORANI-Box. Eine Bestätigung mit allen Details erhältst du per E-Mail.",
    keepBrowsing: "Weiter stöbern",
    toHome: "Zur Startseite",
  },
  notfound: {
    eyebrow: "Fehler 404",
    title: "Hier funkelt nichts.",
    body: "Diese Seite gibt es nicht (mehr). Aber unsere Steine warten woanders auf dich.",
    toShop: "Zum Shop",
    toHome: "Zur Startseite",
  },
};

// EN — inhaltlich gleichwertig, Markenstimme (ruhig, editorial, kein Hype).
const en: typeof de = {
  common: {
    brandTagline: "Real gemstones. Timeless design.",
    allProducts: "All products",
    shopAll: "All pieces",
    viewGemstones: "All gemstones",
    backToShop: "Back to the shop",
    from: "from",
    loading: "Loading …",
  },
  nav: {
    announcement: "Free shipping within Germany · info@lumorani.com",
    shop: "Shop",
    gemstones: "Gemstones",
    giftsets: "Gift sets",
    about: "About",
    start: "Home",
    contact: "Contact",
    search: "Search",
    cart: "Cart",
    menuOpen: "Open menu",
    menuClose: "Close menu",
    langLabel: "Language",
  },
  footer: {
    blurb: "Real gemstones. Timeless design. A family business run by Samir and his father.",
    colCollections: "Collections",
    colService: "Service",
    colLegal: "Legal",
    l_shipping: "Delivery and shipping",
    l_returns: "Returns policy",
    l_faq: "Frequently asked questions",
    l_contact: "Contact",
    l_imprint: "Imprint",
    l_privacy: "Privacy policy",
    l_terms: "Terms",
    l_accessibility: "Accessibility",
    occ_anfang: "For every beginning",
    occ_alltag: "For every day",
    occ_statement: "Statement",
    occ_geschenk: "To gift",
    rights: "LUMORANI",
    handmade: "Handmade in Germany",
  },
  hero: {
    eyebrow: "Real gemstones · Timeless design",
    titleTop: "Jewellery that",
    titleBottom: "carries emotion",
    sub: "For people who like to express themselves with style.",
    ctaPrimary: "Explore the collection",
    ctaSecondary: "View gemstones",
  },
  home: {
    collectionsEyebrow: "Collections",
    collectionsTitle: "The right stone for every moment",
    storyEyebrow: "Our story",
    storyTitle: "Moments that stay",
    storyLead:
      "Jewellery accompanies us through moments that stay. A gift, a beginning, a feeling. That is why we create pieces that carry meaning.",
    storyBody:
      "Chosen with care by Samir and his father, every piece stands for authenticity, depth and character. We believe in clear forms, strong colours and designs that feel like a part of you.",
    storyCta: "About Lumorani",
    newsEyebrow: "New arrivals",
    newsTitle: "Fresh from the workshop",
    quote:
      "Our collection combines deep ruby tones, intense emerald green and clear metallic accents.",
    voicesEyebrow: "Testimonials",
    voicesTitle: "What our customers say",
  },
  trust: {
    handmade: "Handmade",
    handmadeSub: "Crafted with care by hand",
    natural: "Real natural stones",
    naturalSub: "Hand-picked gemstones, each one unique",
    shipping: "Free shipping",
    shippingSub: "Within Germany from €0",
    family: "Family manufactory",
    familySub: "By Samir and his father",
  },
  newsletter: {
    eyebrow: "Newsletter",
    title: "New pieces first.",
    body: "Sign up and be the first to hear about new pieces, rare stones and special moments. No spam — only what truly shines.",
    emailLabel: "Email*",
    emailPlaceholder: "name@mail.com",
    submit: "Sign up",
    thanks: "Thank you. You’ll be the first to hear from us.",
    pending: "Signing you up …",
    consent: "By signing up, you consent to receiving the newsletter. You will only be added after clicking the confirmation link.",
    error: "That didn’t work. Please try again.",
  },
  cart: {
    title: "Cart",
    close: "Close",
    empty: "Nothing selected yet. Discover our favourites.",
    giftWrap: "Gift wrapping (+€0)",
    giftPlaceholder: "Gift message (optional) — we’ll add it by hand.",
    promoPlaceholder: "Voucher code",
    promoHint: "at checkout",
    sum: "Subtotal",
    checkout: "Checkout",
    checkoutLoading: "One moment …",
    reassurance: "Secure payment via Stripe · Insured shipping · 14-day returns",
    errUnavailable: "Checkout is currently unavailable.",
    errNetwork: "Network error. Please try again.",
  },
  shop: {
    crumbShop: "Shop",
    eyebrowShop: "Shop",
    eyebrowCollection: "Collection",
    titleAll: "All jewellery",
    searchLabel: "Search products",
    searchPlaceholder: "Name, gemstone or category",
    showAll: "Show all products",
    filterAll: "All",
    selStone: "Stone",
    selPrice: "Price",
    selSort: "Sort",
    allStones: "All stones",
    priceAll: "All prices",
    priceUnder25: "up to €25",
    price25to60: "€25–60",
    priceOver60: "over €60",
    sortRecommended: "Recommended",
    sortPriceAsc: "Price, low to high",
    sortPriceDesc: "Price, high to low",
    countOne: "piece",
    countMany: "pieces",
    emptyEyebrow: "Not there yet?",
    emptyTitle: "Your stone may still be waiting in Samir’s workshop.",
    emptyBody:
      "We don’t have a finished piece for this selection right now. Tell us what you’re looking for — colour, stone, occasion — and we’ll see what we can find or craft by hand.",
    emptyCta: "Send a custom request",
    resetFilters: "Reset filters",
  },
  product: {
    add: "Add to cart",
    trust1: "Handmade, one of a kind",
    trust2: "Insured shipping",
    trust3: "14-day returns",
    factMaterial: "Material",
    factCharacter: "Character",
    factMaking: "Craft",
    factCare: "Care",
    factDelivery: "Delivery",
    factMaterialFallback: "Natural stone, handcrafted",
    factCharacterFallback: "Hand-picked, one of a kind",
    factMakingValue: "Handmade, one of a kind",
    factCareFallback: "Soft cloth, lukewarm water",
    factDeliveryValue: "3–5 business days, insured",
    samirNote: "Samir’s note",
    samirRole: "Samir · Founder & stone finder",
    related: "Goes well with",
    shotProduct: "Product view",
    shotBox: "In the LUMORANI box",
    shotCollection: "Collection",
  },
  gemstones: {
    eyebrow: "Gemstones",
    title: "The variety of our gemstones",
    subtitle:
      "Chosen with great care — from natural raw stones and precisely faceted crystals to modern “Half & Half” forms. Every stone carries its own energy, structure and character.",
    cutRawT: "Uncut",
    cutRawB: "Raw, natural, authentic. The stone as nature shaped it.",
    cutFacetedT: "Faceted",
    cutFacetedB: "Faceted and polished. Precise edges that break the light.",
    cutHalfT: "Half & Half",
    cutHalfB: "Half raw, half faceted — the contrast for modern, expressive designs.",
    closing:
      "This variety makes our stones ideal for collectors, jewellery lovers, designers and anyone who values special materials.",
  },
  gift: {
    eyebrow: "To gift",
    title: "A gift that stays",
    sub: "Carefully chosen. Wrapped by hand. With meaning. Don’t give an object — give a moment.",
    p1t: "In the LUMORANI box",
    p1b: "Every gift comes wrapped by hand in our emerald-green box with a gold plaque. Packaging may differ slightly from the image.",
    p2t: "With authenticity",
    p2b: "Only real natural stones, hand-picked by Samir. Every piece is one of a kind.",
    p3t: "Insured shipping",
    p3b: "Safely packed, sent insured — and with a 14-day right of return.",
    recEyebrow: "Our recommendation",
    recTitle: "Curated gifts",
    allGifts: "All gifts",
    undecidedEyebrow: "Still undecided?",
    undecidedTitle: "Find the right gift",
    ctaMilestone: "For a milestone",
    ctaEveryday: "For every day",
    ctaByStone: "By stone & meaning",
  },
  success: {
    eyebrow: "Thank you",
    title: "Your order has reached us.",
    body: "We’re now preparing your piece by hand and packing it carefully in the LUMORANI box. You’ll receive a confirmation with all the details by email.",
    keepBrowsing: "Keep browsing",
    toHome: "To the homepage",
  },
  notfound: {
    eyebrow: "Error 404",
    title: "Nothing sparkles here.",
    body: "This page doesn’t exist (any more). But our stones are waiting for you elsewhere.",
    toShop: "To the shop",
    toHome: "To the homepage",
  },
};

export type Dict = typeof de;

const DICT: Record<Locale, Dict> = { de, en };

/** Dictionary für eine Sprache. */
export function getDict(locale: Locale): Dict {
  return DICT[locale];
}
